project_id = "wyiwurjskmtdcwfakels"

[functions.microsoft-auth]
verify_jwt = false

[functions.microsoft-callback]
verify_jwt = false

[functions.basecamp-auth]
verify_jwt = false

[functions.basecamp-callback]
verify_jwt = false

[functions.basecamp-sync]
verify_jwt = true
